# Generated by Django 5.1.4 on 2024-12-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cpf_alunos', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome_evento', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('vagas', models.IntegerField()),
                ('cpf_aluno', models.CharField(max_length=11)),
                ('data_evento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('id_turma', models.IntegerField(primary_key=True, serialize=False)),
                ('modalidade', models.CharField(max_length=50)),
                ('horario', models.TimeField()),
                ('dia_semana', models.CharField(max_length=20)),
                ('faixa_etaria', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('email', 'senha')},
            },
        ),
    ]
